(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./contracts-core.js'):root.ContractsCore);if(typeof module==='object'&&module.exports)module.exports=api;else root.CostReport=api;})(typeof globalThis!=='undefined'?globalThis:this,function(C){
'use strict';
const headers=['CURSO','TURMA','DISCIPLINA','INSTRUTOR','TIPO','DATA INICIAL','DATA FINAL','VALOR DA HORA/AULA','HORAS TOTAIS','VALOR (INSTRUTOR)'];
const names={ADM:'Técnico em Administração',STB:'Técnico em Segurança no Trabalho',ELT:'Técnico em Eletrotécnica',DSI:'Técnico em Desenvolvimento de Sistemas',ELP:'Técnico em Eletroeletrônica',BCV:'Bombeiro Civil',ENF:'Técnico em Enfermagem',RAD:'Técnico em Radiologia',EIC:'Técnico em Estética',FLB:'Técnico em Farmácia'};
function values(item){return [names[item.course]||item.course,C.groupLabel(item),item.discipline,item.instructorSnapshot?.name||'Não informado',({theory:'Teórica',practice:'Prática',both:'Teórica e prática'})[item.type]||'Não informado',item.startDate,item.endDate,item.hourRateCents/100,item.hoursUnits/100,item.amountCents/100];}
const xml=value=>String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const utf8=new TextEncoder();
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function join(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length;}return out;}
// Small uncompressed ZIP writer for the finite OOXML parts; no external service.
function zip(files){const local=[],central=[];let offset=0;for(const [name,text] of Object.entries(files)){const n=utf8.encode(name),body=utf8.encode(text),sum=crc(body);const h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,sum,true);v.setUint32(18,body.length,true);v.setUint32(22,body.length,true);v.setUint16(26,n.length,true);local.push(h,n,body);const ch=new Uint8Array(46),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint16(14,33,true);cv.setUint32(16,sum,true);cv.setUint32(20,body.length,true);cv.setUint32(24,body.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);central.push(ch,n);offset+=h.length+n.length+body.length;}
const dir=join(central),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,Object.keys(files).length,true);ev.setUint16(10,Object.keys(files).length,true);ev.setUint32(12,dir.length,true);ev.setUint32(16,offset,true);return join([...local,dir,end]);}
function xlsx(result,{title,start,end,course='',group=''}){
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const cell=(ref,value,style=0,formula)=>`<c r="${ref}" s="${style}"${typeof value==='number'?'':' t="inlineStr"'}>${formula?`<f>${xml(formula)}</f>`:''}${typeof value==='number'?`<v>${value}</v>`:`<is><t xml:space="preserve">${xml(value)}</t></is>`}</c>`;
const serial=date=>Math.round((Date.parse(date+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000);
const br=date=>date.split('-').reverse().join('/');
const rows=[`<row r="1" ht="30" customHeight="1">${cell('A1',title,1)}</row>`,`<row r="2" ht="25" customHeight="1">${cell('A2',`${br(start)} a ${br(end)} · ${course||'Todos os cursos'} · Turma ${group||'todas'} · Somente aprovados`,6)}</row>`,`<row r="3" ht="42" customHeight="1">${headers.map((h,i)=>cell(String.fromCharCode(65+i)+'3',h,2)).join('')}</row>`];
result.rows.forEach((item,index)=>{const r=index+4;rows.push(`<row r="${r}" ht="48" customHeight="1">${values(item).map((value,i)=>cell(String.fromCharCode(65+i)+r,i===5||i===6?serial(value):value,i===5||i===6?4:i===7||i===9?5:3,i===9?`ROUND(I${r}*H${r},2)`:undefined)).join('')}</row>`);});
const totalRow=4+result.rows.length;rows.push(`<row r="${totalRow}" ht="28" customHeight="1">${cell('A'+totalRow,'VALOR TOTAL',2)}${cell('J'+totalRow,result.total/100,7,result.rows.length?`SUM(J4:J${totalRow-1})`:'0')}</row>`);
const width=[28,24,36,34,18,14,14,19,16,22];
const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J${totalRow}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${width.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.join('')}</sheetData><autoFilter ref="A3:J${Math.max(3,totalRow-1)}"/><mergeCells count="3"><mergeCell ref="A1:J1"/><mergeCell ref="A2:J2"/><mergeCell ref="A${totalRow}:I${totalRow}"/></mergeCells><pageMargins left="0.25" right="0.25" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`;
const xf=(font,fill,border,num=0)=>`<xf numFmtId="${num}" fontId="${font}" fillId="${fill}" borderId="${border}" xfId="0" applyAlignment="1" applyNumberFormat="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>`;
const styles=`<?xml version="1.0"?><styleSheet xmlns="${ns}"><numFmts count="2"><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/><numFmt numFmtId="165" formatCode="&quot;R$&quot; #,##0.00"/></numFmts><fonts count="3"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="12"/><color rgb="FFFFFFFF"/><name val="Arial"/></font><font><b/><sz val="10"/><name val="Arial"/></font></fonts><fills count="5"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF38761D"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FF6AA84F"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE6B8AF"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="8">${xf(0,0,0)}${xf(1,2,1)}${xf(2,3,1)}${xf(0,0,1)}${xf(0,0,1,164)}${xf(0,0,1,165)}${xf(0,0,0)}${xf(2,4,1,165)}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
return zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
'_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
'xl/workbook.xml':`<?xml version="1.0"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Despesas" sheetId="1" r:id="rId1"/></sheets><definedNames><definedName name="_xlnm.Print_Titles" localSheetId="0">'Despesas'!$1:$3</definedName><definedName name="_xlnm.Print_Area" localSheetId="0">'Despesas'!$A$1:$J$${totalRow}</definedName></definedNames><calcPr fullCalcOnLoad="1"/></workbook>`,
'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
'xl/styles.xml':styles,'xl/worksheets/sheet1.xml':sheet});
}
return {headers,values,xlsx};
});
